# Default values for csi-driver-hostpath.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  hostpath:
    repository: kanchishimono/hostpathplugin
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  csiProvisioner:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    pullPolicy: IfNotPresent
    tag: v3.4.0
  nodeDriverRegistrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    pullPolicy: IfNotPresent
    tag: v2.7.0
  livenessProbe:
    repository: registry.k8s.io/sig-storage/livenessprobe
    pullPolicy: IfNotPresent
    tag: v2.9.0

kubeletDir: /var/lib/kubelet

driver:
  name: hostpath.csi.kanchi.github.io
  dataDir: /var/lib/hostpath.csi.kanchi.github.io/data

controller:
  replicaCount: 1
  logLevel: 5
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  csiProvisioner:
    logLevel: 5
    resources: {}
  livenessProbe:
    healthPort: 9808
    resources: {}

node:
  maxUnavailable: 1
  logLevel: 5
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  nodeDriverRegistrar:
    logLevel: 5
    resources: {}
  livenessProbe:
    healthPort: 9809
    resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
